---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-test-matrix
name: "🧪 Python Test"
description: "Test a Python Project, generate coverage report"

inputs:
  # Mandatory
  # A matrix Python build version should be passed as input
  PYTHON_VERSION:
    description: "Python version used to run test"
    required: true
    type: string
  # Optional
  NEVER_FAIL:
    description: "Continue even when a test fails"
    required: false
    type: boolean
    default: false
  REPORT_ARTEFACT:
    description: "Store test/coverage report as artefact"
    required: false
    type: boolean
    default: false
  TESTS_PATH:
    description: "Folder containing Python tests"
    required: false
    type: string
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Harden the runner used by this workflow
    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Set up Python ${{ inputs.python_version }}"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: "Install test dependencies"
      id: install-dependencies
      shell: bash
      run: |
        # Install test dependencies
        echo "Upgrading: pip"
        python -m pip install -q --upgrade pip
        echo "Installing: pytest, pytest-cov"
        python -m pip install --disable-pip-version-check -q pytest pytest-cov
        if [ -f pyproject.toml ]; then
          echo "Installing dependencies from: pyproject.toml"
          pip install -q .
        fi
        if [ -f requirements.txt ]; then
          echo "Installing dependencies from: requirements.txt"
          pip install -q -r requirements.txt
        fi

    # ToDo: Run tests with TOX
    # Detect tox.ini
    # Parse file for test stanza
    # Use tox if configured for tests
    # Otherwise proceed to regular method (pytest)

    - name: "Setup failure handling"
      shell: bash
      run: |
        # Setup failure handling
        NEVER_FAIL=$(echo ${{ inputs.NEVER_FAIL }} |\
        tr '[:upper:]' '[:lower:]')
        if [ "f$NEVER_FAIL" = "ftrue" ]; then
          echo "never_fail=true" >> "$GITHUB_ENV"
        fi

    - name: "Run tests and generate coverage report [NEVER FAIL]"
      if: ${{ env.NEVER_FAIL }} == 'true'
      shell: bash
      run: |
        # Run tests and generate coverage report
        if [ -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
          echo "Test path: ${{ inputs.path_prefix }}${{ inputs.tests_path }}"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}${{ inputs.tests_path }}" || true
        elif [ -d ${{ inputs.path_prefix }}tests ]; then
          echo "Test path: tests"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}tests" || true
        elif [ -d ${{ inputs.path_prefix }}test ]; then
          echo "Test path: test"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}test" || true
        else
          echo "Error: path to tests could not be located ❌"
        fi

    - name: "Run tests and generate coverage report [WILL FAIL]"
      if: ${{ env.NEVER_FAIL }} != 'true'
      shell: bash
      run: |
        # Run tests and generate coverage report
        if [ -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
          echo "Test path: ${{ inputs.path_prefix }}${{ inputs.tests_path }}"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
        elif [ -d ${{ inputs.path_prefix }}tests ]; then
          echo "Test path: tests"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}tests"
        elif [ -d ${{ inputs.path_prefix }}test ]; then
          echo "Test path: test"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}test"
        else
          echo "Error: path to tests could not be located ❌"
          exit 1
        fi
    - name: "Create ZIP archive of coverage report"
      shell: bash
      run: |
        # Create ZIP archive of coverage report
        REPORT_ARTEFACT=$(echo ${{ inputs.REPORT_ARTEFACT }} |\
        tr '[:upper:]' '[:lower:]')
        if [ "f$REPORT_ARTEFACT" = "ftrue" ]; then
          if [ -d coverage_report ]; then
            echo "Creating ZIP file of HTML coverage report"
            zip -r test_coverage_report-${{ inputs.python_version }}.zip coverage_report
          else
            echo "No coverage report directory exists"
          fi
        fi
        echo "report_artefact=$REPORT_ARTEFACT" >> "$GITHUB_ENV"

    - name: "Upload test/coverage report"
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      if: env.REPORT_ARTEFACT == 'true'
      with:
        name: test_coverage_report-${{ inputs.python_version }}.zip
        path: test_coverage_report-${{ inputs.python_version }}.zip
        retention-days: 90
