---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-project-test-matrix
name: "🧪 Python Test"
description: "Test a Python Project, generate coverage report"

inputs:
  # Mandatory
  PYTHON_VERSION:
    # A matrix Python build version should be passed as input
    description: "Python version used to run test"
    required: true
    type: string
  # Optional
  PERMIT_TEST_FAIL:
    description: "Continue even when a test fails"
    required: false
    type: boolean
    default: false
  REPORT_ARTEFACT:
    description: "Store test/coverage report as artefact"
    required: false
    type: boolean
    default: false
  TESTS_PATH:
    description: "Folder containing Python tests"
    required: false
    type: string
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Harden the runner used by this workflow
    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Setup action/environment"
      shell: bash
      run: |
        # Setup action/environment
        if [ -n "${{ inputs.path_prefix }}" ] && [ ! -d "${{ inputs.path_prefix }}" ]; then
          echo "Error: invalid path/prefix to project directory ❌"
          exit 1
        fi
        if [ -n "${{ inputs.tests_path }}" ] && \
          [ ! -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
          echo "Error: invalid path/prefix to test directory ❌"
          echo "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
          exit 1
        PERMIT_TEST_FAIL=$(echo "${{ inputs.PERMIT_TEST_FAIL }}" |\
        tr '[:upper:]' '[:lower:]')
        if [ "f$PERMIT_TEST_FAIL" = "ftrue" ]; then
          echo "Warning: test failures will be permitted ⚠️"
          echo "PERMIT_TEST_FAIL=true" >> "$GITHUB_ENV"
        fi

        # Install modules required for testing
        echo "Installing test tooling: pytest, pytest-cov ⬇️"
        python -m pip install --disable-pip-version-check -q pytest pytest-cov
        echo "Installing project dependencies ⬇️"
        if [ -f "${{ inputs.path_prefix }}pyproject.toml" ]; then
          echo "Source: ${{ inputs.path_prefix }}pyproject.toml"
          pip install -q "${{ inputs.path_prefix }}pyproject.toml"
        fi
        if [ -f "${{ inputs.path_prefix }}requirements.txt" ]; then
          echo "Source: ${{ inputs.path_prefix }}requirements.txt"
          pip install -q -r "${{ inputs.path_prefix }}requirements.txt"
        fi
        if [ -z "${{ inputs.python_version }}" ]; then
          echo "Error: Python version was not provided ❌"
          exit 1
        else
          echo "Using Python: ${{ inputs.python_version }} 🐍"
        fi

    - name: "Set up Python ${{ inputs.python_version }}"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ inputs.python_version }}

    # ToDo: Implement test using TOX
    # Check for presence of tox.ini
    # Parse file for test stanza
    # Use tox if configured for tests
    # Otherwise proceed to regular method (pytest)

    - name: "Run tests and generate coverage report [NEVER FAIL]"
      if: ${{ env.PERMIT_TEST_FAIL }} == 'true'
      shell: bash
      run: |
        # Test folder has been specified
        if [ -n "${{ inputs.tests_path }}" ]; then
          TEST_PATH="${{ inputs.path_prefix }}${{ inputs.tests_path }}"
        # Otherwise use common locations
        elif [ -d "${{ inputs.path_prefix }}tests" ]; then
          TEST_PATH="${{ inputs.path_prefix }}tests"
        elif [ -d "${{ inputs.path_prefix }}test" ]; then
          TEST_PATH="${{ inputs.path_prefix }}test"
        else
          echo "Error: no valid test path was found ❌"
          exit 1
        fi
        pytest --cov --cov-report=html:coverage_report "$TEST_PATH" || true

    - name: "Run tests and generate coverage report [WILL FAIL]"
      if: ${{ env.PERMIT_TEST_FAIL }} != 'true'
      shell: bash
      run: |
        # Run tests and generate coverage report
        if [ -d "${{ inputs.path_prefix }}${{ inputs.tests_path }}" ]; then
          echo "Test path: ${{ inputs.path_prefix }}${{ inputs.tests_path }}"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}${{ inputs.tests_path }}"
        elif [ -d ${{ inputs.path_prefix }}tests ]; then
          echo "Test path: tests"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}tests"
        elif [ -d ${{ inputs.path_prefix }}test ]; then
          echo "Test path: test"
          pytest --cov --cov-report=html:coverage_report \
            "${{ inputs.path_prefix }}test"
        else
          echo "Error: path to tests could not be located ❌"
          exit 1
        fi

    - name: "Create ZIP archive of coverage report"
      shell: bash
      run: |
        # Create ZIP archive of coverage report
        REPORT_ARTEFACT=$(echo ${{ inputs.REPORT_ARTEFACT }} |\
        tr '[:upper:]' '[:lower:]')
        if [ "f$REPORT_ARTEFACT" = "ftrue" ]; then
          if [ -d coverage_report ]; then
            echo "Creating ZIP file of HTML coverage report"
            zip -r test_coverage_report-${{ inputs.python_version }}.zip coverage_report
          else
            echo "No coverage report directory exists"
          fi
        fi
        echo "report_artefact=$REPORT_ARTEFACT" >> "$GITHUB_ENV"

    - name: "Upload test/coverage report"
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      if: env.REPORT_ARTEFACT == 'true'
      with:
        name: test_coverage_report-${{ inputs.python_version }}.zip
        path: test_coverage_report-${{ inputs.python_version }}.zip
        retention-days: 90
