---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# python-twine-check-action
name: "📦 Twine Check Artefacts"
description: "Verifies Python build artefacts can be uploaded to PyPI"
# Checks supported filenames and file types prior to publishing

inputs:
  PATH:
    description: "Directory/folder containing Python build artefacts"
    required: true
    default: "dist"

runs:
  using: "composite"
  steps:
    - id: twine-check
      name: "Check Artefacts with Twine"
      shell: bash
      run: |
        # Run twine check against build artefacts
        echo -n "Installing Python tool: twine"
        pip install --disable-pip-version-check -q --upgrade twine
        echo "Path to check: ${{ inputs.path }}"
        echo "Running: twine check ${{ inputs.path }}/*"
        if (twine check ${{ inputs.path }}/*); then
          echo "Checked Artefacts with Twine ✅"
        else
          echo "Artefacts failed Twinecheck ❌"
          exit 1
        fi
