---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🤖 Dependabot Updates"

version: 2
updates:
  # prettier-ignore
  - package-ecosystem: "pip"
    # prettier-ignore
    directory: "/" # Location of package manifests
    commit-message:
      prefix: "[dependabot] Chore:"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # prettier-ignore
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[dependabot] Chore:"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
