---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "Dependabot"

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    commit-message:
      prefix: "[dependabot] Chore:"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "[dependabot] Chore:"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
