---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🛠️ Get default GIT branch"

outputs:
  DEFAULT_BRANCH:
    description: "Default branch name of repository"

runs:
  using: "composite"
  steps:
    - name: "Get repository default GIT branch"
      shell: bash
      run: |
        # Get repository default GIT branch
        DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"

        # The github.ref_name context variable is only available when
        # the workflow is triggered by a push event to a branch or tag
        EVENT_REF_NAME="${{ github.event.ref_name }}"
        if [ -z "$DEFAULT_BRANCH" ]; then
          echo "Default branch value was NOT populated ❌"; exit 1
        fi
        echo "Repository default branch: $DEFAULT_BRANCH ✅" >> "$GITHUB_STEP_SUMMARY"
        echo "Repository default branch: $DEFAULT_BRANCH ✅"

        if [ -n "${{ github.ref_name }}" ];then
          echo "github.ref_name: ${{ github.ref_name }}"
        fi
        if [ -n "${{ github.event.ref_name }}" ];then
          echo "github.event.ref_name: ${{ github.event.ref_name }}"
        fi
        if [ -n "${{ github.event.pull_request.head.ref }}" ];then
          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
        fi
        if [ -n "${{ github.event.pull_request.base.ref }}" ];then
          echo "github.event.pull_request.base.ref: ${{ github.event.pull_request.base.ref }}"
        fi
        if [ -n "${{ github.event.release.tag_name }}" ];then
         echo "github.event.release.tag_name: ${{ github.event.release.tag_name }}"
        fi

        # Return results
        echo "default_branch=$DEFAULT_BRANCH" >> "$GITHUB_ENV"
        echo "default_branch=$DEFAULT_BRANCH" >> "$GITHUB_OUTPUT"
