---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🏷️ Check/Inject Issue-ID"

inputs:
  ISSUE_ID_LOOKUP_JSON:
    description: "JSON lookup table mapping users to JIRA tickets"
    type: string
    required: true

outputs:
  PRESENT:
    description: "Whether the Issue-ID string is present"
    value: ${{ steps.fetch.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: "Check commit message for required string"
      id: check
      shell: bash
      run: |
        # Check commit message for required string
        TMPFILE=$(mktemp -p /tmp --suffix "-commit-message-body.txt")
        echo "${{ steps.retrieve.outputs.commit_message }}" >> "$TMPFILE"

        # Gerrit reg-ex expression is:
        # Issue-ID: ([A-Z][A-Z0-9]{1,9}-\\d+)

        if [[ "${{ steps.retrieve.outputs.commit_message }}" =~ "Issue-ID: " ]]; then
          echo "✅ Issue-ID was found in the pull request"
          echo "PRESENT=true" >> "$GITHUB_ENV"
          echo "PRESENT=true" >> "$GITHUB_OUTPUT"
        else
          echo "❌ Issue-ID was NOT found in the pull request"
          echo "PRESENT=false" >> "$GITHUB_ENV"
          echo "PRESENT=false" >> "$GITHUB_OUTPUT"
        fi

    - name: "Looking up appropriate JIRA ticket for this change"
      id: lookup
      shell: bash
      run: |
        set -vx

        # Look up appropriate JIRA ticket for this change
        echo "Looking up appropriate JIRA ticket for this change"
        ACTOR="${{ github.actor }}"
        ACTOR_ID="${{ github.actor_id }}"
        echo "Actor: $ACTOR [$ACTOR_ID]"

        # Validate lookup table contents
        ISSUE_ID_LOOKUP_JSON='${{ inputs.ISSUE_ID_LOOKUP_JSON }}'
        if [ -z "${{ inputs.ISSUE_ID_LOOKUP_JSON }}" ]; then
          echo "The required lookup JSON/variable is not set: ISSUE_ID_LOOKUP_JSON"; exit 1
        else
          echo "Lookup table:"
          echo "$ISSUE_ID_LOOKUP_JSON"
        fi

        JQ=$(which jq || true)
        if [ -x "$JQ" ]; then
          KEY="$ACTOR"
          '${{ inputs.ISSUE_ID_LOOKUP_JSON }}' > table.json
          echo "File contents:"
          cat table.json
          # yamllint disable-line rule:line-length
          VALUE=$(echo '${{ inputs.ISSUE_ID_LOOKUP_JSON }}' | jq -r --arg KEY "$KEY" '.[] | select(.key==$KEY) | .value')
          if [ -z "$VALUE" ]; then
            echo "The key/value lookup failed"; exit 1
          fi
          echo "Key/value lookup returned:"
          echo "$VALUE"
        else
          echo "Error: jq command was NOT found in the PATH"; exit 1
        fi
        echo "issue_id=$VALUE" >> GITHUB_ENV
        echo "issue_id=$VALUE" >> GITHUB_OUTPUT
        echo "### Inserting Issue-ID: $VALUE 🏷️" >> "$GITHUB_STEP_SUMMARY"

    - name: "Injecting Issue-ID into body of first commit message"
      id: inject
      if: env.present == 'false'
      shell: bash
      run: |
        # Injecting Issue-ID into body of first commit
        echo "Injecting Issue-ID into body of first commit"
