---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# python-project-setup-action
name: "🛠️ Python Project Setup"
description: "Extracts Python project metadata from repository"

outputs:
  # Enumerated values
  PYTHON_PROJECT_NAME:
    description: "The name of the Python project from pyproject.toml or setup.py"
    value: ${{ steps.project-naming.outputs.python_project_name }}
  PYTHON_BUILD_NAME:
    # Any dashes in the name will be replaced with underscores
    description: "The name of the Python project when built"
    value: ${{ steps.project-naming.outputs.python_build_name }}
  VERSIONING_TYPE:
    description: "Project supported Python versions as JSON"
    value: ${{ steps.versioning-type.outputs.versioning_type }}
  MATRIX_JSON:
    description: "Project supported Python versions as JSON"
    value: ${{ steps.supported-python-versions.outputs.matrix_json }}
  BUILD_PYTHON_VERSION:
    description: "Python version to use for build (creates artefacts)"
    value: "${{ steps.supported-python-versions.outputs.base_python }}"

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Extract Python project naming"
      id: project-naming
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-project-name-action@main

    - name: "Determine versioning type [static|dynamic]"
      id: versioning-type
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-versioning-type-action@main

    - name: "Extract Python supported versions (JSON)"
      id: supported-python-versions
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-supported-versions-action@main

    - name: "Display summary output"
      shell: bash
      run: |
        # Display summary output
        echo "# 🐍 Python Project" >> "$GITHUB_STEP_SUMMARY"

        echo "Gathered Python project metadata"

        echo "| Key | Value |" >> "$GITHUB_STEP_SUMMARY"
        echo "| -------- | ------- |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Project name | ${{ steps.project-naming.outputs.python_project_name }} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Package name | ${{ steps.project-naming.outputs.python_build_name }} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Versioning type | ${{ steps.versioning-type.outputs.versioning_type }} |" >> "$GITHUB_STEP_SUMMARY"
        echo "| Build Python | ${{ steps.supported-python-versions.outputs.build_python_version }} |" \
          >> "$GITHUB_STEP_SUMMARY"

        echo "### Python versions JSON for matrix jobs" >> "$GITHUB_STEP_SUMMARY"
        echo "${{ steps.supported-python-versions.outputs.matrix_json }}" >> "$GITHUB_STEP_SUMMARY"
