---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🔍 Repository Inspection"
description: "Scans repository content and identifies supported content"

outputs:
  REPO_PYTHON_PROJECT:
    description: "Repository contains a Python project with file: pyproject.toml"
    value: ${{ steps.classification.outputs.python_project }}
  REPO_NODE_JS_PROJECT:
    description: "Repository contains a Node.js project with file: package.json"
    value: ${{ steps.classification.outputs.node_js_project }}
  REPO_MAVEN_CONFIG:
    description: "Repository contains Maven project with file: pom.xml"
    value: ${{ steps.classification.outputs.maven_config }}
  REPO_GRADLE_CONFIG:
    description: "Repository contains Gradle project with file(s): settings.gradle*"
    value: ${{ steps.classification.outputs.gradle_config }}
  REPO_JUPYTER_NOTEBOOKS:
    description: "Repository contains Jupyter Notebooks with file(s): *.ipynb"
    value: ${{ steps.classification.outputs.jupyter_notebooks }}
  REPO_TOX_CONFIG:
    description: "Repository contains a TOX configuration file: tox.ini"
    value: ${{ steps.classification.outputs.tox_config }}

runs:
  using: "composite"
  steps:
    - name: "Inpect repository content"
      id: classification
      shell: bash
      run: |
        #/usr/bin/env bash
        # Inpect repository content

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
          TMPFILE=$(mktemp -p /tmp --suffix "github-summary-output.txt")
          export GITHUB_STEP_SUMMARY="$TMPFILE"
        fi

        # Check for Python project metadata files
        if [ -f pyproject.toml ] || [ -f setup.py ]; then
          REPO_PYTHON_PROJECT="true"
        else
          REPO_PYTHON_PROJECT="false"
        fi

        # Check for Node.JS package description
        if [ -f package.json ]; then
          REPO_NODE_JS_PROJECT="true"
        else
          REPO_NODE_JS_PROJECT="false"
        fi

        # Check for Maven config: pom.xml
        if [ -f pom.xml ]; then
          REPO_MAVEN_CONFIG="true"
        else
          REPO_MAVEN_CONFIG="false"
        fi

        # Check for Gradle settings files: settings.gradle*
        GRADLE_COUNT=$(find . -name 'settings.gradle*' | wc -l )
        if [ "$GRADLE_COUNT" -ne 0 ]; then
          REPO_GRADLE_CONFIG="true"
        else
          REPO_GRADLE_CONFIG="false"
        fi

        # Check for TOX configuration: tox.ini
        if [ -f tox.ini ]; then
          REPO_TOX_CONFIG="true"
        else
          REPO_TOX_CONFIG="false"
        fi

        # Check for Jupyter Notebooks: *.ipynb
        NOTEBOOK_COUNT=$(find . -name '*.ipynb' | wc -l )
        if [ "$NOTEBOOK_COUNT" -ne 0 ]; then
          REPO_JUPYTER_NOTEBOOKS="true"
        else
          REPO_JUPYTER_NOTEBOOKS="false"
        fi

        ### Set Outputs ###

        echo "python_project=$REPO_PYTHON_PROJECT" >> "$GITHUB_OUTPUT"
        echo "node_js_project=$REPO_NODE_JS_PROJECT" >> "$GITHUB_OUTPUT"
        echo "maven_config=$REPO_MAVEN_CONFIG" >> "$GITHUB_OUTPUT"
        echo "gradle_config=$REPO_GRADLE_CONFIG" >> "$GITHUB_OUTPUT"
        echo "tox_config=$REPO_TOX_CONFIG" >> "$GITHUB_OUTPUT"
        echo "jupyter_notebooks=$REPO_JUPYTER_NOTEBOOKS" >> "$GITHUB_OUTPUT"

        ### GitHub Summary ###

        echo '# 🔍 Repository Content Inspection' >> "$GITHUB_STEP_SUMMARY"

        # The hack below helps make the displayed output summary pretty

        for VARIABLE in $(declare | grep REPO); do
          VAR_NAME=$(echo "$VARIABLE" | awk -F= '{print $1}')
          VAR_BOOLEAN=$(echo "$VARIABLE" | awk -F= '{print $2}')

          # The string subsitution below makes output easier to read
          # sed -e 's/true/✅/' -e 's/false/❌/'
          if [ $VAR_BOOLEAN = "true" ]; then
            VAR_BOOLEAN="✅"
          else
            VAR_BOOLEAN="❌"
          fi
          export $VAR_NAME=$VAR_BOOLEAN
        done

        echo "Supported content types are listed in the table below" >> "$GITHUB_STEP_SUMMARY"

        echo "| Status | Support Content Type |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_PYTHON_PROJECT | Python Project |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_NODE_JS_PROJECT | Node.js Project |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_MAVEN_CONFIG | Maven Configuration |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_GRADLE_CONFIG | Gradle Configuration |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_TOX_CONFIG | Tox Configuration |" >> "$GITHUB_STEP_SUMMARY"
        echo "| $REPO_JUPYTER_NOTEBOOKS | Jupyter Notebooks |" >> "$GITHUB_STEP_SUMMARY"

        # Displays summary text to the terminal when run from a shell
        if [ -f "$TMPFILE" ]; then
          cat "$TMPFILE"
        fi

        #SHELLCODEEND
