---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# file-sed-regex-action
name: "Runs SED and applies RegEx to a file"
description: "Applies a regular expression to a file using the SED command"

inputs:
  FLAGS:
    description: "Flags to use with SED command"
    required: false
    default: "-i"
  REGEX:
    description: "Regular expression to use"
    required: true
  PATH:
    description: "Filesystem path to local file"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Running SED command on: ${{ inputs.PATH }}"
      id: sed
      shell: bash
      run: |
        # Running SED command on: ${{ inputs.PATH }}
        SED_CMD=$(which sed)
        if [ ! -x "$SED_CMD" ]; then
          echo "Error: sed command not in PATH"; exit 1
        fi
        FILE_PATH="${{ inputs.PATH }}"
        if [ ! -f $FILE_PATH ]; then
          echo "Error: file not found [$FILE_PATH] ❌"; exit 1
        fi
        set -o noglob
        if ($SED_CMD '${{ inputs.FLAGS }}' '${{ inputs.REGEX }}' "$FILE_PATH"); then
          echo "sed command was successful ✅ "
        else
          echo "Error: command failed with exit status: $? ❌"
        fi
