---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🐍 Patch Python Project Metadata/Version"

inputs:
  STRING:
    description: "New version string"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name:
      id: update-version
      uses: os-climate/osc-github-devops/.github/actions/file-sed-regex@main

    - name: "Substituting project version string"
      shell: bash
      run: |
        # Substituting project version string

        #SHELLCODESTART

        # Allows for testing from a local shell
        if [ -z "$GITHUB_OUTPUT" ]; then
          echo "Running from a shell, NOT workflow"
          export GITHUB_OUTPUT="/dev/null"
          export GITHUB_ENV="/dev/null"
          if [ $# -ne 1 ]; then
            echo "Error: invalid arguments specified"
            echo "Usage:  $0 [string]"; exit 1
          else
            STRING="$1"
          fi
        else
          STRING=${{ inputs.STRING }}
        fi

        if [ -z "$STRING" ]; then
          echo "Error: string input was NOT received"
          echo "Check the calling workflow syntax and setup..."; exit 1
        fi
        echo "New version string to insert: $STRING"

        # Attempt version string substitution for project
        sed -i -E "s:^version =.*$:version = \"$TARGET\":" pyproject.toml



        # Check to see if the above succeeded
        if !(grep -q "version = \"$TARGET\"" pyproject.toml); then
          echo "Error: failed version substitution in pyproject.toml"; exit 1
        fi

        #SHELLCODEEND

    - name: "Substituting project version string"
      shell: bash
      run: |
        # Validate file was updated

        # Check to see if the above succeeded
        if !(grep -q "version = \"$TARGET\"" pyproject.toml); then
          echo "Error: failed version substitution in pyproject.toml"; exit 1
        fi
