---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🏷️ Repository Tag Create"
# Create a tag in the repository

inputs:
  TAG:
    description: "Tag to create in repository"
    required: false
  PRERELEASE:
    description: "Tag release as a development release"
    # Will use context awareness if NOT explicitly set
    required: false
    type: boolean
    default: true
  GITHUB_TOKEN:
    description: "Required to push new tags to the repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Evaluate action/workflow context"
      shell: bash
      run: |
        # Evaluate action/workflow context

        TAG="${{ inputs.TAG }}"
        PRERELEASE="${{ inputs.PRERELEASE }}"

        if [ -n "$TAG" ]; then
          TAG="v0.0.0"
        fi

        if [ "$PRERELEASE" = "true" ]; then
          echo "Tag to create: $TAG [development]"
        else
          echo "Tag to create: $TAG [production]"
        fi

        # NOT IMPLEMENTED YET
        # Evaluate commit message contents for release type
        if [ ${{ contains(github.event.head_commit.message, '[release]') }} ]; then
          echo "Possible production release?"
        elif [ ${{ contains(github.event.head_commit.message, '[development]') }} ]; then
          echo "Possible development release?"
        fi

        echo "tag=$TAG" >> "$GITHUB_ENV"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        echo "prerelease=$PRERELEASE" >> "$GITHUB_ENV"
        echo "prerelease=$PRERELEASE" >> "$GITHUB_OUTPUT"

    - name: "Add tag to repository: ${{ env.TAG }}"
      id: create-tag
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        prerelease: ${{ env.PRERELEASE }}
        tag_name: ${{ env.TAG }}
