---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# standalone-linting-action
name: "Standalone Linting"
description: "Runs linting tools that do NOT run under pre-commit.ci"

inputs:
  CONFIG_URL:
    description: "Download location for standalone linting configuration file"
    type: string
    required: false
    # yamllint disable-line rule:line-length
    default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/pre-commit-config.yaml"
  DEPENDENCIES_URL:
    description: "Download location for Python dependencies"
    type: string
    required: false
    # yamllint disable-line rule:line-length
    default: "https://raw.githubusercontent.com/os-climate/osc-github-devops/refs/heads/main/.github/actions/standalone-linting-action/requirements.txt"
  FORCE_REMOTE:
    description: "Ignore local linting configuration; always install from remote"
    type: string
    required: false
    default: "false"

#
env:
  python-version: "3.12"

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ env.python-version }}
        cache: "pip"

    - name: "Checkout repository"
      # yamllint disable-line rule:line-length
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Install pre-commit, check prerequisites"
      shell: bash
      run: |
        # Install pre-commit, check prerequisites
        pip install --disable-pip-version-check --upgrade pre-commit
        CURL_CMD=$(which curl)
        if [ ! -x "$CURL_CMD" ]; then
         echo "cURL binary not found ❌"; exit 1
        fi

    - name: "Check for local linting configuration"
      if: inputs.force_remote != 'true'
      id: local-precommit-config
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@473a3c654d58fa0c27f91a9cc25bd9433de43d5e # v0.2.4
      with:
        path: ".pre-commit-config.yaml"

    - name: "Download remote pre-commit configuration"
      # yamllint disable-line rule:line-length
      if: steps.local-precommit-config.outputs != 'file' || inputs.force_remote == 'true'
      shell: bash
      run: |
        # Download remote pre-commit configuration
        echo "Downloading configuration from:"
        echo "${{ inputs.CONFIG_URL }}"
        # cURL will overwrite any pre-existing local file
        curl -sS -o .pre-commit-config.yaml "${{ inputs.CONFIG_URL }}"
        echo "Pre-commit configuration file downloaded ✅"

    #    - name: "Download/install Python dependencies"
    #      # yamllint disable-line rule:line-length
    #      shell: bash
    #      if: steps.local-precommit-config.outputs != 'file' || inputs.force_remote == 'true'
    #      run: |
    #        # Download Python dependencies file
    #        echo "Downloading configuration from:"
    #        echo "${{ inputs.DEPENDENCIES_URL }}"
    #        curl -sS -o /tmp/requirements.txt "${{ inputs.DEPENDENCIES_URL }}"
    #        echo "Python dependencies file downloaded ✅"
    #        echo "Installing Python dependencies and pre-commit"
    #        pip install --disable-pip-version-check --upgrade -r /tmp/requirements.txt

    - name: "Validate configuration"
      shell: bash
      run: |
        # Validate configuration
        pre-commit validate-config

    - name: "Run all pre-commit hooks"
      shell: bash
      run: |
        # Run all pre-commit hooks
        if [ ! -d .mypy_cache ]; then /bin/mkdir .mypy_cache; fi
        pre-commit run -a
