---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# standalone-linting-action
name: "Standalone Linting"
description: "Runs linting tools that do NOT run under pre-commit.ci"

inputs:
  CONFIG_URL:
    description: "Download location for standalone linting configuration file"
    type: string
    required: false
    # yamllint disable-line rule:line-length
    default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/pre-commit-config.yaml"
  DEPENDENCIES_URL:
    description: "Download location for additional Python dependencies"
    type: string
    required: false
  REMOTE_CONFIG:
    description: "Ignore local linting configuration; always install from remote"
    type: string
    required: false
    default: "true"
  PYTHON-VERSION:
    description: "Python version used to run pre-commit hooks"
    type: string
    required: false
    # Needs to be maintained; best practice is pass explicitly to setup-python
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      # yamllint disable-line rule:line-length
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Setup Python"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: "Install pre-commit"
      run: pip install --disable-pip-version-check pre-commit

    - name: "Check prerequisites"
      shell: bash
      run: |
        # Check prerequisites
        CURL_CMD=$(which curl)
        if [ ! -x "$CURL_CMD" ]; then
         echo "cURL binary not found ❌"; exit 1
        fi

    - name: "Check for local linting configuration"
      if: inputs.REMOTE_CONFIG != 'true'
      id: local-precommit-config
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@473a3c654d58fa0c27f91a9cc25bd9433de43d5e # v0.2.4
      with:
        path: ".pre-commit-config.yaml"

    - name: "Download remote pre-commit configuration"
      # yamllint disable-line rule:line-length
      if: steps.local-precommit-config.outputs != 'file' || inputs.REMOTE_CONFIG == 'true'
      shell: bash
      run: |
        # Download remote pre-commit configuration
        echo "Downloading configuration from:"
        echo "${{ inputs.CONFIG_URL }}"
        # cURL will overwrite any pre-existing local file
        curl -sS -o .pre-commit-config.yaml "${{ inputs.CONFIG_URL }}"
        echo "Pre-commit configuration file downloaded ✅"

    - name: "Download Python dependencies configuration"
      if: inputs.DEPENDENCIES_URL != ''
      shell: bash
      run: |
        # Download Python dependencies configuration
        echo "Downloading configuration from:"
        echo "${{ inputs.DEPENDENCIES_URL }}"
        if (curl -sS -o /tmp/requirements.txt "${{ inputs.DEPENDENCIES_URL }}"); then
          echo "Python dependencies file downloaded ✅"
        else
          echo "Error: unable to download Python dependencies configuration ❌"; exit 1
        fi

    - name: "Install additional Python dependencies"
      if: inputs.DEPENDENCIES_URL != ''
      run: pip install --disable-pip-version-check -r /tmp/requirements.txt

    - name: "Validate configuration"
      shell: bash
      run: |
        # Validate configuration
        pre-commit validate-config

    - name: "Run all pre-commit hooks"
      shell: bash
      run: |
        # Run all pre-commit hooks
        if [ ! -d .mypy_cache ]; then /bin/mkdir .mypy_cache; fi
        pre-commit run -a
