---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"

exclude: |
  (?x)^(
      docs\/conf.py|
      dco-signoffs/$
  )$

repos:
  - repo: local
    hooks:
      - id: mypy-cache
        name: "create mypy cache"
        language: system
        pass_filenames: false
        entry: bash -c 'if [ ! -d .mypy_cache ]; then mkdir .mypy_cache; fi'

  - repo: https://github.com/pre-commit/mirrors-mypy
    # Manually managed version
    rev: "v1.14.1"
    hooks:
      - id: mypy
        verbose: true
        args: ["--show-error-codes", "--install-types", "--non-interactive"]
        additional_dependencies: ["pytest", "types-requests"]
