---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# python-build-action
name: "🐍 Build Python Project"
description: "Builds a Python Project"

inputs:
  # Optional
  ARTEFACT_PATH:
    description: "Build artefacts will be output to this folder/directory"
    required: false
    default: "dist"
  PURGE_ARTEFACT_PATH:
    description: "Purge target artefact path prior to builds"
    required: false
    default: "false"
  TAG:
    description: "Tag version/name for this specific build (semantic)"
    required: false
  ATTESTATIONS:
    # Attestations should not be used for development builds
    description: "Apply GitHub attestations to artefacts"
    required: false
    default: "false"
  SIGSTORE_SIGN:
    # Signing should not be used for development builds
    description: "Sign build artefacts with Sigstore"
    required: false
    default: "false"
  PATH_PREFIX:
    description: "Directory location containing project code"
    type: string
    required: false
    default: ""

outputs:
  MATRIX_JSON:
    description: "Project supported Python versions as JSON"
    value: ${{ steps.python-metadata.outputs.matrix_json }}
  ARTEFACT_NAME:
    description: "Build artefacts will be output to this folder/directory"
    value: ${{ steps.python-metadata.outputs.python_project_name }}
  ARTEFACT_PATH:
    description: "Build artefacts will be output to this folder/directory"
    value: ${{ steps.python-metadata.outputs.matrix_json }}

runs:
  using: "composite"
  steps:
    # Harden the runner used by this workflow
    # yamllint disable-line rule:line-length
    - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
      with:
        egress-policy: audit

    # yamllint disable-line rule:line-length
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Build summary heading"
      shell: bash
      run: |
        # Build summary heading
        echo "# 🐍 Python Build" >> "$GITHUB_STEP_SUMMARY"

    - name: "Gather Python project metadata"
      id: python-metadata
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-project-metadata-action@34d653e17fbd4e4685c505dd2000cbf5836d4ff5 # v0.1.2
      with:
        path_prefix: "${{ inputs.path_prefix }}"

    # Catch this error as soon as possible
    - name: "Check project version matches pushed tags"
      if: startsWith(github.ref, 'refs/tags/')
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-project-tag-push-verify-action@27478ec0a2d9acc3a3dc80da4648f4d1eb9d429e # v0.1.0
      with:
        path_prefix: "${{ inputs.path_prefix }}"

    - name: "Build versioning"
      id: versioning
      if: inputs.tag
      shell: bash
      run: |
        # Explicit build versioning
        echo "Explicit build versioning: ${{ inputs.tag }}"
        echo "tag=${{ inputs.tag }}" >> "$GITHUB_ENV"

    - name: "Patch project versioning metadata"
      if: env.python_project_version != inputs.tag
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-project-version-patch-action@37c1be5e5e1923632c568c8227a39a13c644bffe # v0.1.0
      with:
        replacement_version: ${{ env.tag }}
        path_prefix: "${{ inputs.path_prefix }}"

    - name: "Set up Python ${{ inputs.build_python_version }}"
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version-file: "${{ inputs.path_prefix }}pyproject.toml"

    - name: "Install PDM tooling"
      # yamllint disable-line rule:line-length
      uses: pdm-project/setup-pdm@b2472ca4258a9ea3aee813980a0100a2261a42fc # v4.2
      with:
        python-version-file: "${{ inputs.path_prefix }}pyproject.toml"

    - name: "Build Python project"
      id: perform-build
      shell: bash
      run: |
        # Build Python project
        if [ -n ${{ inputs.path_prefix }} ]; then
          echo "Change to project directory: ${{ inputs.path_prefix }}"
          cd ${{ inputs.path_prefix }}
        fi

        # Set build parameters/variables
        echo "Action triggered by: ${GITHUB_TRIGGERING_ACTOR}"
        datetime=$(date +'%Y-%m-%d-%H%M')
        echo "Build date and time stamp: $datetime"
        echo "datetime=$datetime" >> "$GITHUB_ENV"
        echo "datetime=${datetime}" >> "$GITHUB_OUTPUT"

        if [ ${{ inputs.PURGE_OUTPUT_PATH }} ] && \
           [ -d ${{ inputs.ARTEFACT_PATH }} ]; then
          echo "Purging artefact output path prior to build ⚠️"
          echo "Path: ${{ inputs.ARTEFACT_PATH }}"
          rm -Rf ${{ inputs.ARTEFACT_PATH }}/*
        fi

        python -m pip install --disable-pip-version-check -q --upgrade pip

        # PDM Build
        if [ -f pyproject.toml ]; then
          echo "Found file: pyproject.toml"
          echo "Building with: pdm build --dest ${{ inputs.ARTEFACT_PATH }}"
          if (pdm build --dest ${{ inputs.ARTEFACT_PATH }}); then
            echo "Build with PDM successful ✅"
          else
            echo "Build with PDM failed ❌"; exit 1
          fi

        # TOX Build
        elif [ -f tox.ini ]; then
          echo "Found TOX configuration file: tox.ini"
          echo "Attempting to install TOX..."
          python -m pip install --disable-pip-version-check \
            -q --upgrade tox tox-gh-actions
          echo "Attempting build with: tox -e build"
          echo "WARNING: assumes build artefact path is valid"
          if (tox -e build); then
            echo "Build with TOX successful ✅"
          else
            echo "Build with TOX failed ❌"; exit 1
          fi

        # Build with Python module
        else
          echo "Neither file found: tox.ini/pyproject.toml"
          echo "Attempting build with: python -m build"
          python -m pip install --disable-pip-version-check -q --upgrade build
          if (python -m build --outdir ${{ inputs.ARTEFACT_PATH }}); then
            echo "Build with Python module successful ✅"
          else
            echo "Build with Python module failed ❌"; exit 1
          fi
        fi

    - name: "Build summary"
      shell: bash
      run: |
        # Build summary
        echo "artefact_name=${{ env.python_project_name }}" >> "$GITHUB_OUTPUT"
        echo "artefact_path=${{ inputs.ARTEFACT_PATH }}" >> "$GITHUB_OUTPUT"
        echo "Artefact name: ${{ env.python_project_name }}"
        echo "Artefact path: ${{ inputs.ARTEFACT_PATH }}"
        VERSION=$(python --version)
        echo "Build with $VERSION successful ✅"
        echo "Build with $VERSION successful ✅" >> "$GITHUB_STEP_SUMMARY"

    # Note: caution with sequencing of steps
    # Twine validation after attestations/signing causes failures
    - name: "Validate artefacts with Twine"
      # yamllint disable-line rule:line-length
      uses: lfreleng-actions/python-twine-check-action@e72540b7947abcb1634408728ee8946738d85b2b # v0.1.0

    - name: "Artefact attestation for: ${{ inputs.ARTEFACT_PATH }}"
      # yamllint disable-line rule:line-length
      uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2.1.0
      if: ${{ inputs.attestations == 'true' }}
      with:
        subject-path: ${{ inputs.ARTEFACT_PATH }}/*

    - name: "Add heading to separate signing from attestations"
      if: ${{ inputs.sigstore_sign == 'true' }}
      shell: bash
      run: |
        # Add heading to separate signing from attestations
        echo "### Sigstore Signing ✍🏼" >> "$GITHUB_STEP_SUMMARY"

    - name: "Sign packages with SigStore"
      if: ${{ inputs.sigstore_sign == 'true' }}
      # yamllint disable-line rule:line-length
      uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46 # v3.0.0
      env:
        package-path: ${{ inputs.ARTEFACT_PATH }}
      with:
        inputs: >-
          ./${{ inputs.ARTEFACT_PATH }}/*.tar.gz
          ./${{ inputs.ARTEFACT_PATH }}/*.whl

    - name: "Upload build artefacts"
      # yamllint disable-line rule:line-length
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: ${{ env.python_project_name }}
        path: ${{ inputs.ARTEFACT_PATH }}
        if-no-files-found: error
