---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# github-release-action
name: "📦 GitHub Release"
description: "Creates a new GitHub release"

inputs:
  # Mandatory
  TAG:
    description: "Semantic tag for this release/build"
    type: string
    required: true
  TOKEN:
    description: "Required to push new tags to the repository"
    required: true
  # Optional
  PROJECT_NAME:
    description: "Project/product name"
    type: string
    # When not provided, defaults to repository name
    required: false
  RELEASE_TITLE:
    description: "Title of release/product"
    type: string
    required: false
    # When not provided, defaults to project name followed by pushed tag
    # e.g. osc-github-devops v1.0.0
  PRERELEASE:
    description: "Mark release as pre-release/development version"
    type: string
    required: false
    default: false
  ARTEFACT_PATH:
    description: "Path/location for build artefacts"
    type: string
    required: false
  MAKE_LATEST:
    description: "Mark as latest release in the repository"
    # See: https://github.com/softprops/action-gh-release
    # Can be either: true, false, or legacy
    type: string
    required: false
    default: false
  GH_RELEASE_DISABLE:
    description: "Dry run, do NOT perform the release step"
    type: string
    required: false
    default: false

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Extract project/repository naming"
      id: naming
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/project-name-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9

    - name: "Verify release tag"
      id: tag-validate
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/tag-validate-semantic-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      with:
        tag: ${{ inputs.tag }}

    - name: "Check action environment"
      shell: bash
      run: |
        # Check action environment
        if [ -z "${{ inputs.token }}" ]; then
          echo "Error: token must be passed as input to composite action 🛑"
          echo "Error: token must be passed as input to composite action 🛑" \
            >> "$GITHUB_STEP_SUMMARY"
          exit 1
        else
          # This is THE ONLY way to make the token available to softprops/action-gh-release
          echo "GITHUB_TOKEN=${{ inputs.token }}" >> "$GITHUB_ENV"
        fi
        # Build tag values
        if [ ${{ steps.tag-validate.outputs.semantic }} == 'true' ]; then
          pushed_tag="${{ inputs.tag }}"
        else
          echo "Release tag NOT semantic: ${{ inputs.tag }} ❌"
          echo "Release tag NOT semantic: ${{ inputs.tag }} ❌" \
            >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
        if [ -z "${{ inputs.PROJECT_NAME }}" ]; then
          PROJECT_NAME="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
        else
          PROJECT_NAME="${{ inputs.PROJECT_NAME }}"
        fi
        echo "PROJECT_NAME=$PROJECT_NAME" >> "$GITHUB_ENV"
        if [ -z "${{ inputs.RELEASE_TITLE }}" ]; then
          echo "RELEASE_TITLE=$PROJECT_NAME ${{ inputs.tag }}" >> "$GITHUB_ENV"
        else
          echo "RELEASE_TITLE=${{ inputs.RELEASE_TITLE }}" >> "$GITHUB_ENV"
        fi

    - name: "⬇ Download build artefacts [conditional]"
      if: inputs.artefact_path != ''
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        # ToDo: check if this is used/needed and all setup/pre-requisites
        # Such as environment variables are configured correctly
        name: ${{ env.project_name }}
        path: ${{ inputs.artefact_path }}

    - name: "Check if tag/version already released"
      id: release-validate
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/github-list-releases-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      with:
        tag: ${{ inputs.tag }}

    - name: "Abort when tag/version already released"
      shell: bash
      if: steps.release-validate.outputs.released == 'true'
      # yamllint disable-line rule:line-length
      run: |
        # Abort with error when tag already released
        echo "⛔️ ## Aborting: tag ${{ inputs.tag }} already released" >> "$GITHUB_STEP_SUMMARY"
        echo "🔗 https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ inputs.tag }}" \
          >> "$GITHUB_STEP_SUMMARY"
        exit 1

    - name: "GitHub release [with artefacts]"
      if: inputs.artefact_path != '' && inputs.GH_RELEASE_DISABLE == 'false'
      # Note: a bug in release v2.2.0 causes upload failures
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        prerelease: ${{ inputs.prerelease }}
        make_latest: ${{ inputs.MAKE_LATEST }}
        tag_name: ${{ inputs.tag }}
        name: ${{ env.RELEASE_TITLE }}
        # ToDo: Incorporate release notes, etc.
        # body_path: ${{ github.workspace }}/CHANGELOG.rst
        files: |
          ${{ inputs.artefact_path }}/*

    - name: "GitHub release [no artefacts]"
      if: inputs.artefact_path == '' && inputs.GH_RELEASE_DISABLE == 'false'
      # Note: a bug in release v2.2.0 causes upload failures
      uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
      with:
        prerelease: ${{ inputs.prerelease }}
        make_latest: ${{ inputs.MAKE_LATEST }}
        tag_name: ${{ inputs.tag }}
        name: ${{ env.RELEASE_TITLE }}

    - name: "Print summary/job output"
      shell: bash
      # yamllint disable rule:line-length
      run: |
        # Print summary/job output
        if [ "${{ inputs.GH_RELEASE_DISABLE }}" != 'false' ]; then
          echo "## GitHub Releasing Disabled: Dry Run 🛑" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "# 🚀 GitHub Release" >> "$GITHUB_STEP_SUMMARY"
          echo "Title: ${{ env.RELEASE_TITLE }}" >> "$GITHUB_STEP_SUMMARY"
          echo "🔗 https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ inputs.tag }}" >> "$GITHUB_STEP_SUMMARY"
          # ToDo: Add release notes here
          if [ "${{ inputs.prerelease }}" = "true" ]; then
            echo "Test/Development Build ✅"
          else
            echo "Production Release Build ✅"
          fi
        fi
