---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "📦 GitHub Release"

inputs:
  # Mandatory
  BUILD_TAG:
    description: "Semantic tag for this release/build"
    type: string
    required: true
  GITHUB_TOKEN:
    description: "Required to push new tags to the repository"
    required: true
  # Optional
  PRERELEASE:
    description: "Mark release as pre-release/development version"
    type: string
    required: false
    default: false
  ARTEFACT_LOCATION:
    description: "Path/location for build artefacts"
    type: string
    required: false
    default: "dist"
  MAKE_LATEST:
    description: Marks this release as the latest release"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Verify pushed tag"
      id: tag-validate
      uses: os-climate/osc-github-devops/.github/actions/tag-validate-semantic@main
      with:
        tag: ${{ inputs.build_tag }}

    - name: "Report pushed tag"
      shell: bash
      run: |
        # Pushed tag values
        if [ ${{ steps.tag-validate.outputs.semantic }} == 'true' ]; then
          pushed_tag="${{ inputs.build_tag }}"
          echo "Pushed tag semantic: ${{ inputs.build_tag }} ✅"
          echo "Pushed tag semantic: ${{ inputs.build_tag }} ✅" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "The pushed tag was NOT semantic: ${{ inputs.build_tag }} ❌"
          echo "The pushed tag was NOT semantic: ${{ inputs.build_tag }} ❌" >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi

    - name: "⬇ Download build artefacts [conditional]"
      if: inputs.artefact_location != ''
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: ${{ env.python_project_name }}
        path: ${{ inputs.artefact_location }}

    - name: "GitHub release [with artefacts]"
      if: inputs.artefact_location != ''
      uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v.2.2.0
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        prerelease: ${{ inputs.prerelease }}
        make_latest: ${{ inputs.MAKE_LATEST }}
        tag_name: ${{ inputs.build_tag }}
        name: ${{ inputs.tag }}"
        # ToDo: Incorporate release notes, etc.
        # body_path: ${{ github.workspace }}/CHANGELOG.rst
        files: |
          ${{ inputs.artefact_location }}/**

    - name: "GitHub release [no artefacts]"
      if: inputs.artefact_location == ''
      uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v.2.2.0
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        prerelease: ${{ inputs.prerelease }}
        make_latest: ${{ inputs.MAKE_LATEST }}
        tag_name: ${{ inputs.build_tag }}
        name: ${{ inputs.tag }}"

    - name: "Print summary/job output"
      shell: bash
      run: |
        # Print summary/job output
        echo "# 🚀 GitHub Release" >> "$GITHUB_STEP_SUMMARY"
        echo "Build version/tag: ${{ inputs.build_tag }}" >> "$GITHUB_STEP_SUMMARY"
        if [ "${{ inputs.prerelease }}" = "true" ]; then
          echo "Pre-release/Development Build: ✅"
        else
          echo "Production/Release Build: ✅"
        fi
