---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# tag-validate-semantic-action
name: "🏷️ Check Tag/Version string is Semantic"
description: "Validates a given string for conformity to semantic value"

inputs:
  # Mandatory
  TAG:
    description: "Tag/version string to check/verify"
    required: true

outputs:
  # Mandatory
  SEMANTIC:
    description: "Set true if tag passes semantic versioning check"
    value: ${{ steps.validate.outputs.semantic }}

runs:
  using: "composite"
  steps:
    - name: "Validate tag/string is semantic"
      id: validate
      shell: bash
      run: |
        # Validate tag/string is semantic
        echo "String to check: $TAG"
        # Strip leading "v" character if present
        if [[ "$TAG" == v* ]] || [[ "$TAG" == V* ]]; then
          TAG="${TAG:1}"
        fi

        # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
        # See: https://regex101.com/r/Ly7O1x/3/
        PATTERN="^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$"

        # Validate supplied (and parsed) tag
        if ! [[ "$TAG" =~ $PATTERN ]]; then
          echo "Tag/version string is NOT semantic/valid ❌"
          RESULT="false"
        else
          echo "Tag/version string is semantic/valid ✅"
          RESULT="true"
        fi
        echo "semantic=$RESULT" >> $GITHUB_OUTPUT
