---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "📌 Pinned Versions Action"
description: "Verifies action/workflow calls are pinned to SHA commit values"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: ${{ github.event_name == 'workflow_dispatch' }}

    - name: Checkout pull request
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: ${{ github.event_name != 'workflow_dispatch' }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Get changed files
      if: ${{ github.event_name != 'workflow_dispatch' }}
      id: changed-files
      # yamllint disable-line rule:line-length
      uses: tj-actions/changed-files@bab30c2299617f6615ec02a68b9a40d10bd21366 # v45.0.5
      with:
        since_last_remote_commit: true
        files: |
          .github/**/*.{yml,yaml}

    - name: Prune files NOT changed in pull request
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        # Prune files NOT changed in pull request
        find .github -type f -name '*.yaml' -o -name '*.yml' > listed.txt
        for YAMLFILE in ${ALL_CHANGED_FILES}; do
          echo "$YAMLFILE" >> changed.txt
        done
        if [ ! -f changed.txt ]; then
          echo "No changes in scope for audit"; exit 0
        fi
        grep -Fvf changed.txt listed.txt > excluded.txt
        while IFS= read -r YAMLFILE
        do
          mv "$YAMLFILE" "$YAMLFILE.excluded"
        done < excluded.txt
        echo "Files to process:"
        find .github -type f -name '*.yaml' -o -name '*.yml'

    - name: "Ensure SHA pinned actions"
      # yamllint disable-line rule:line-length
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@5d6ac37a4cef8b8df67f482a8e384987766f0213 # v3.0.17
