---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# pinned-versions-action
name: "📌 Pinned Versions Action"
description: "Verifies action/workflow calls are pinned to SHA commit values"

runs:
  using: "composite"
  steps:
    # Checkout repository on manual invocation
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: ${{ github.event_name == 'workflow_dispatch' }}

    # Checkout change when invoked on a pull request
    - name: Checkout pull request
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: ${{ github.event_name != 'workflow_dispatch' }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    # Get files changed in the pull request from an action
    - name: Get changed files from action
      if: github.event_name != 'workflow_dispatch'
      id: changed-files-action
      # yamllint disable-line rule:line-length
      uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45.0.6
      with:
        since_last_remote_commit: true
        files: |
          .github/**/*.{yml,yaml}

    # Create a list of files changed in the pull request
    - name: Create a list of changed files
      if: github.event_name != 'workflow_dispatch'
      id: changed-files-list
      shell: bash
      run: |
        # 📄 Create a list of changed files
        for YAMLFILE in ${ALL_CHANGED_FILES}; do
          echo "$YAMLFILE" >> changed.txt
        done

    - name: Set verification scope
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      shell: bash
      run: |
        # ✂️ Prune unmodified workflows/actions from scope

        # When no action/workflow files were changed in the pull request
        # There is nothing to do, so exit early without an error
        if [ ! -f changed.txt ]; then
          echo "workflow_changes=false" >> "$GITHUB_ENV"
          echo "No changes in scope for check ⏩"; exit 0
        fi

        # Manual invocation, all files considered changed and will be checked
        if [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          cp repository.txt changed.txt
          echo "workflow_changes=true" >> "$GITHUB_ENV"
          echo "All GitHub actions/workflows will be checked ✅"; exit 0
        fi

        # Selective checks; prune unmodified actions/workflows from scope
        grep -Fvf changed.txt repository.txt > unmodified.txt
        while IFS= read -r YAMLFILE
        do
          rm "$YAMLFILE"
        done < unmodified.txt
        echo "workflow_changes=true" >> "$GITHUB_ENV"
        echo "Selectively checking actions/workflows ✅"
        cat changed.txt

    - name: "Ensure SHA pinned actions"
      # yamllint disable-line rule:line-length
      uses: zgosalvez/github-actions-ensure-sha-pinned-actions@c3a2b64f69b7a1542a68f44d9edbd9ec3fc1455e # v3.0.20
      if: env.workflow_changes == 'true'
