---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "💬 GIT Commit Message"

inputs:
  REF:
    description: "GIT ref to checkout"
    required: false
    default: ${{ github.head_ref }}
  FETCH_DEPTH:
    description: "Fetch depth to checkout"
    required: false
    default: 0

outputs:
  COMMIT_MESSAGE:
    description: "GIT commit message"
    value: ${{ steps.return.outputs.commit_message }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      #with:
      #  ref: ${{ inputs.REF }}
      #  fetch-depth: ${{ inputs.FETCH_DEPTH }}

    - name: "GIT commit message"
      id: return
      shell: bash
      run: |
        # GIT commit message
        COMMIT_MESSAGE=$(git show -s --format='%B')
        echo "COMMIT_MESSAGE<<EOF"$'\n'"$COMMIT_MESSAGE"$'\n'EOF >> "$GITHUB_ENV"
        echo "COMMIT_MESSAGE<<EOF"$'\n'"$COMMIT_MESSAGE"$'\n'EOF >> "$GITHUB_OUTPUT"
        echo "💬 GIT Commit Message"
        echo "$COMMIT_MESSAGE"
