---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🐍 Get Python Project Name"
description: "Returns the name of the Python Project"

outputs:
  PYTHON_PROJECT_NAME:
    description: "The name of the Python project from pyproject.toml or setup.py"
    value: ${{ steps.python-project-name.outputs.python_project_name }}
  PYTHON_BUILD_NAME:
    # Any dashes in the name will be replaced with underscores
    description: "The name of the Python project when built"
    value: ${{ steps.python-project-name.outputs.python_build_name }}

runs:
  using: "composite"
  steps:
    - uses: os-climate/osc-github-devops/.github/actions/path-check@main
      id: setup-py
      with:
        check_path: "setup-py"

    - uses: os-climate/osc-github-devops/.github/actions/path-check@main
      id: pyproject-toml
      with:
        check_path: "pyproject.toml"

    - name: "Use project name from setup.py"
      if: ${{ steps.setup-py.outputs.present }} == 'true'
      uses: os-climate/osc-github-devops/.github/actions/file-grep-regex@main
      with:
        # https://regex101.com/r/YcYBKD/1
        flags: "-oP -m1"
        regex: '''(?<=name = ")([^"]*)'''
        filename: "setup.py"

    - name: "Use project name from pyproject.toml"
      if: ${{ steps.pyproject-toml.outputs.present }} == 'true'
      uses: os-climate/osc-github-devops/.github/actions/file-grep-regex@main
      with:
        # https://regex101.com/r/AZ80qK/1
        flags: "-oP -m1"
        regex: '''(?<=name = ")([^"]*)'''
        filename: "pyproject.toml"

    - name: "Throw error if Python project metadata was NOT found"
      if: ${{ steps.pyproject-toml.outputs.present }} == 'false' &&
        ${{ steps.setup-py.outputs.present }} == 'false'
      shell: bash
      run: |
        # Throw error if Python project metadata was NOT found
        echo "Neither pyproject.toml NOT setup.py were found"; exit 1

    - name: "Return extracted values"
      shell: bash
      run: |
        # Return extracted values

        PYTHON_PROJECT_NAME="$EXTRACTED_STRING"
        echo "PYTHON_PROJECT_NAME: $PYTHON_PROJECT_NAME"

        # Replace all dashes in the name with underscores
        PYTHON_BUILD_NAME=$(echo "$PYTHON_PROJECT_NAME" | tr '-' '_')
        echo "PYTHON_BUILD_NAME: $PYTHON_BUILD_NAME"

        # Make available to the GitHub environment
        echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_ENV"
        echo "python_project_name=$PYTHON_PROJECT_NAME" >> "$GITHUB_OUTPUT"
        echo "python_build_name=$PYTHON_BUILD_NAME" >> "$GITHUB_ENV"
        echo "python_build_name=$PYTHON_BUILD_NAME" >> "$GITHUB_OUTPUT"
