---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# repository-tag-create-action
name: "🏷️ Repository Tag Create"
description: "Creates a new tag in the repository"

inputs:
  TAG:
    description: "Tag to create in repository"
    required: true
  PRERELEASE:
    description: "Tag release as a development release"
    required: false
    type: boolean
    default: false
  MAKE_LATEST:
    description: "Mark as latest release in the repository"
    # See: https://github.com/softprops/action-gh-release
    # Can be either: true, false, or legacy
    type: string
    required: false
    default: false
  GITHUB_TOKEN:
    description: "Required to push new tags to the repository"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Check tag is semantic"
      id: validate
      uses: lfit/releng-reusable-workflows/.github/actions/tag-validate-semantic-action@main
      with:
        tag: ${{ inputs.tag }}

    - name: "Abort when tag is NOT semantic"
      if: ${{ steps.outputs.validate.semantic }} == 'false'
      shell: bash
      run: |
        # Abort workflow when tag is NOT semantic
        echo "Abort workflow when tag is NOT semantic: ${{ inputs.TAG }} ❌"
        echo "### Abort workflow when tag is NOT semantic: ${{ inputs.TAG }} ❌" \
           >> "$GITHUB_STEP_SUMMARY"
        exit 1

    - name: "Add tag to repository: ${{ inputs.TAG }}"
      id: create-tag
      uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974 # v2.1.0
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        prerelease: ${{ inputs.PRERELEASE }}
        tag_name: ${{ inputs.TAG }}
        make_latest: ${{ inputs.MAKE_LATEST }}
