---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# github-list-releases-action
name: "📦 List GitHub Releases"
description: "Returns a list of releases for the current repository"

inputs:
  DISPLAY_IN_SUMMARY:
    description: "Displays list in summary output"
    required: false
    default: "false"
    type: string
  INCLUDE_PRE_RELEASES:
    description: "Includes pre-release builds in output"
    required: false
    default: "false"
    type: string

runs:
  using: "composite"
  steps:
    - name: "Placeholder output"
      shell: bash
      run: |
        # Placeholder output
        echo "# Placeholder for: 📦 List GitHub Releases"
        echo "# Placeholder for: 📦 List GitHub Releases" >> "$GITHUB_STEP_SUMMARY"
