---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🏷️ Current/Latest Repository Tag"

inputs:
  TYPE:
    description: "Returns the current/latest tag from repository [all|production|development]"
    required: false
    type: string
    default: "all"

outputs:
  TAG_COUNT:
    description: "The number of tags in this repository"
    value: ${{ steps.fetch.outputs.count }}
  TAG:
    # The leading non-numeric "v" character will be stripped
    description: "Return the latest semantic tag from repository"
    value: ${{ steps.results.outputs.tag }}
  VTAG:
    description: "The tag [with v prefix] e.g. v1.2.3"
    value: ${{ steps.results.outputs.vtag }}
  SEMANTIC:
    description: "Set true if current tag is semantic"
    value: ${{ steps.validate.outputs.semantic }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: "Fetch tags"
      id: fetch
      shell: bash
      if: startsWith(github.ref, 'refs/tags/') != true
      # Don't fetch tags if a tag was pushed, it will result in an error, e.g.
      # Fetching tags...
      # From https://github.com/os-climate/osc-github-devops
      #  * [new branch]      main       -> origin/main
      #  * [new tag]         v0.0.0     -> v0.0.0
      #  ! [rejected]        v0.0.2     -> v0.0.2  (would clobber existing tag)
      run: |
        # Workaround for: https://github.com/actions/checkout/issues/1471
        echo "Fetching tags..."
        git fetch --tags
        TAG_COUNT=$(git tag -l | wc -l)
        echo "tag_count=$TAG_COUNT" >> "$GITHUB_ENV"
        echo "tag_count=$TAG_COUNT" >> "$GITHUB_OUTPUT"

    - name: "Warning: no tags currently found in repository"
      if: env.tag_count == '0'
      shell: bash
      run: |
        echo "Warning: no tags currently found in repository ❌"
        echo "Warning: no tags currently found in repository ❌" >> "$GITHUB_STEP_SUMMARY"

    - name: "Return latest tag"
      if: env.tag_count != '0'
      id: retrieve
      shell: bash
      run: |
        # Return latest tag
        TAG=$(git tag -l --sort=committerdate | grep -o '?*.*.*' | sort -rV | head -1 || true)

        if [ ${{ env.tag_count}} == '0' ]; then
          TAG="0.0.0"
        elif [ ${{ inputs.TYPE }} = "all" ]; then
          TAG=$(git tag -l --sort=committerdate | grep -o '?*.*.*' | \
          sort -rV | head -1 || true)
        elif [ ${{ inputs.TYPE }} = "production" ]; then
          TAG=$(git tag -l --sort=committerdate | grep -o '?*.*.*' | \
          grep -Ev '(dev|alpha|beta|test)' | sort -rV | head -1 || true)
        elif [ ${{ inputs.TYPE }} = "development" ]; then
          TAG=$(git tag -l --sort=committerdate | grep -o '?*.*.*' | \
          grep -E '(dev|pre|beta|test|alpha)' | sort -rV | head -1 || true)
        fi

        # If present, strip the leading "v" character
        if [[ "$TAG" == v* ]] || [[ "$TAG" == V* ]]; then
          TAG="${TAG:1}"
        fi

        echo "tag: ${TAG} [v${TAG}]"
        echo "Current repository tag: ${TAG} [v${TAG}] 🏷️" >> "$GITHUB_STEP_SUMMARY"
        echo "tag=${TAG}" >> "$GITHUB_ENV"
        echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
        echo "vtag=v${TAG}" >> "$GITHUB_ENV"
        echo "vtag=v${TAG}" >> "$GITHUB_OUTPUT"

    - name: "Check semantic/validity"
      id: validate
      uses: os-climate/osc-github-devops/.github/actions/tag-validate-semantic@main
      with:
        tag: ${{ env.tag }}

    - name: "Set flag if semantic"
      id: report
      shell: bash
      run: |
        # Set flag if semantic
        if [ "${{ steps.validate.outputs.semantic }}" = "true" ]; then
          echo "semantic=true" >> "$GITHUB_ENV"
          echo "semantic=true" >> "$GITHUB_OUTPUT"
          echo "Tag is semantic ✅" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "semantic=false" >> "$GITHUB_ENV"
          echo "semantic=false" >> "$GITHUB_OUTPUT"
          echo "Tag is NOT semantic ❌" >> "$GITHUB_STEP_SUMMARY"
        fi
