---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

name: "🛠️ Python Project Setup"
description: "Extracts required project metadata"

outputs:
  # Enumerated values
  PYTHON_PROJECT_NAME:
    description: "The name of the Python project from pyproject.toml or setup.py"
    value: ${{ steps.project-naming.outputs.python_project_name }}
  PYTHON_BUILD_NAME:
    # Any dashes in the name will be replaced with underscores
    description: "The name of the Python project when built"
    value: ${{ steps.project-naming.outputs.python_build_name }}
  VERSIONING_TYPE:
    description: "Project supported Python versions as JSON"
    value: ${{ steps.versioning-type.outputs.versioning_type }}
  MATRIXJSON:
    description: "Project supported Python versions as JSON"
    value: ${{ steps.versions-matrix.outputs.matrixjson }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: "Extract Python project naming"
      id: project-naming
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-project-name@main

    - name: "Determine versioning type [static|dynamic]"
      id: versioning-type
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-versioning-type@main

    - name: "Extract Python supported versions (JSON)"
      id: versions-matrix
      # yamllint disable-line rule:line-length
      uses: os-climate/osc-github-devops/.github/actions/python-versions-matrix@main
