---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "🐍 Check Project Version matches Tag"
description: "Verify Python project metadata version matches {{ github.ref_name }}"

outputs:
  MATCH:
    description: "Set true when pushed tags match version from pyproject.toml"
    value: ${{ steps.verify.outputs.match }}

runs:
  using: "composite"
  steps:
    - name: "Retrieve project version"
      id: fetch
      uses: os-climate/osc-github-devops/.github/actions/python-project-version-action@main

    - name: "Check tag/versions for consistency"
      id: verify
      shell: bash
      run: |
        # Check tag/versions for consistency

        PROJECT_VERSION="${{ steps.fetch.outputs.python_project_version }}"
        if [ -z "$PROJECT_VERSION" ]; then
          echo "The python project version string was empty ❌"
          echo "Check action/workflow inputs and variables"
          echo "Verify parsing of python project metadata?"
          exit 1
        fi

        # Get version from pushed tag
        TAG_VERSION="${{ github.ref_name }}"
        echo "Version from project metadata: $PROJECT_VERSION"
        echo "Version from tag push: $TAG_VERSION"

        # Compare the two version strings
        if [ "$TAG_VERSION" = "$PROJECT_VERSION" ]; then
          echo "Pushed tag matches version from pyproject.toml ✅"
          echo "match=true" >> "$GITHUB_ENV"
          echo "match=true" >> "$GITHUB_OUTPUT"
        else
          echo "Pushed tag does NOT match version from pyproject.toml ❌"
          echo "match=false" >> "$GITHUB_ENV"
          echo "match=false" >> "$GITHUB_OUTPUT"
        fi
