---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# python-project-version-patch-action
name: "🐍 Replaces/Updates Python Project Version String"
description: "Updates the Python project metadata version string"
# Note: Works for either pyproject.toml or setup.py

inputs:
  REPLACEMENT_VERSION:
    description: "New version string"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    # yamllint disable-line rule:line-length
    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      id: setup-py
      with:
        path: "setup.py"

    # yamllint disable-line rule:line-length
    - uses: lfit/releng-reusable-workflows/.github/actions/path-check-action@9b845102d5158f0b80bd53405a0b6855b26dc4a0 # v0.2.9
      id: pyproject-toml
      with:
        path: "pyproject.toml"

    - name: "Patch Python project version: setup.py"
      id: patch-version-setup-py
      if: steps.setup-py.outputs.type == 'file'
      uses: lfreleng-actions/file-sed-regex-action@8b6ab94c60adb3d87bbc5ecd81fc3c55dc9516af # v0.1.0
      with:
        flags: "-i -E"
        regex: 's:version=.*$:version="${{ inputs.REPLACEMENT_VERSION }}":'
        path: "setup.py"

    - name: "Patch Python project version: pyproject.toml"
      id: patch-version-pyproject-toml
      if: steps.pyproject-toml.outputs.type == 'file'
      uses: lfreleng-actions/file-sed-regex-action@main
      with:
        flags: "-i -E"
        regex: 's:^version =.*$:version = "${{ inputs.REPLACEMENT_VERSION }}":'
        path: "pyproject.toml"
