---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "Inventory Report"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  inventory:
    name: "Inventory Report"
    runs-on: ubuntu-24.04
    permissions:
      # We want to report on various aspects of the repository content
      actions: read
      contents: read
      issues: read
      pull-requests: read
      security-events: read
    steps:
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: "Run repository inventory"
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/repository-inventory-action@main
        with:
          inventory_location: ${{ secrets.INVENTORY_LOCATION }}
          inventory_deploy_key: ${{ secrets.INVENTORY_DEPLOY_KEY }}
