---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "!.github/"
    branches:
      - "*"
      - "!update-devops-tooling"

permissions: {}

jobs:
  linting:
    name: "Standalone linting check"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Linting action
        uses: os-climate/osc-github-devops/.github/actions/linting-action@main
