---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: 🔐 Security Audits
on:
  workflow_dispatch:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: "31 3 * * 0"
  push:
    branches: ["main", "master"]
    paths:
      - "**"
      - "!.github/**"

# Declare default permissions as none.
permissions: {}

jobs:
  openssf-scorecard:
    name: "OSSF Scorecard Audit"
    runs-on: ubuntu-24.04
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
      # Uncomment the permissions below if installing in a private repository.
      # contents: read
      # actions: read
    steps:
      - name: "OSSF Scorecard Audit"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/openssf-scorecard-audit-action@main # ToDo: temporary during testing
