---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation <https://linuxfoundation.org>

# Packages a development/production release on GitHub
name: "📦 [R] GitHub Python Release"

on:
  workflow_call:
    inputs:
      # Mandatory
      BUILD_TAG:
        description: "Semantic tag for this release/build"
        type: string
        required: true
      # Optional
      PROJECT_NAME:
        description: "Project/product name"
        type: string
        # When not provided, defaults to repository name
        required: false
      RELEASE_TITLE:
        description: "Title of release/product"
        type: string
        required: false
        # When not provided, defaults to project name followed by pushed tag
        # e.g. osc-github-devops v1.0.0
      PRERELEASE:
        description: "Mark release as pre-release/development version"
        type: string
        required: false
        default: false
      ARTEFACT_LOCATION:
        description: "Path/location for build artefacts"
        type: string
        required: false
        default: "dist"
      MAKE_LATEST:
        description: "Mark as latest release in the repository"
        # See: https://github.com/softprops/action-gh-release
        # Can be either: true, false, or legacy
        type: string
        required: false
        default: false

permissions: {}

jobs:
  github-release:
    name: "GitHub release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "⬇ Download build artefacts"
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.project_name }}
          path: ${{ inputs.artefact_location }}

      - name: "Check project version matches pushed tags"
        if: startsWith(github.ref, 'refs/tags/')
        uses: os-climate/osc-github-devops/.github/actions/python-project-version-vs-tag@main

      - name: "GitHub Release"
        uses: os-climate/osc-github-devops/.github/actions/github-release-action@main
        with:
          project_name: ${{ env.python_project_name }}
          artefact_location: "dist"
          build_tag: ${{ inputs.build_tag }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
