---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Runs tests on a Python project for a number of specified Python versions"
name: "🧪 [R] Python Tests"

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        # Usually specified/extracted from the file: pyproject.toml
        description: "Python matrix versions to use for test builds (in JSON)"
        required: true
        type: string

permissions: {}

jobs:
  python-test-matrix:
    name: "Python tests"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Set up Python ${{ inputs.python_version }}"
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: "Test Python project"
        id: python-project-tests
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/python-test-project@main
        with:
          python_version: ${{ inputs.python_version }}
          never_fail: true
          report_artefact: true
