---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Checks the commit message body for an Issue-ID, adds one when NOT present
name: "🎟️ [R] Inject Issue-ID"

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  github-pr:
    name: "Inject Issue-ID"
    runs-on: "ubuntu-latest"
    if: vars.ISSUE_ID_LOOKUP_JSON != ''
    permissions:
      contents: write
    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: os-climate/osc-github-devops/.github/actions/inject-issue-id-action@main # Testing locally
        with:
          issue_id_lookup_json: ${{ vars.ISSUE_ID_LOOKUP_JSON }}
