---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ [R] Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      CONFIG_URL:
        description: "Download location for standalone linting configuration file"
        type: string
        required: false
        # yamllint disable-line rule:line-length
        default: "https://raw.githubusercontent.com/lfit/releng-reusable-workflows/refs/heads/main/.github/actions/standalone-linting-action/pre-commit-config.yaml"
      DEPENDENCIES_URL:
        description: "Download location for additional Python dependencies"
        type: string
        required: false
      REMOTE_CONFIG:
        description: "Ignore local linting configuration; always install from remote"
        type: string
        required: false
        default: "true"
      PYTHON-VERSION:
        description: "Python version used to run pre-commit hooks"
        type: string
        required: false
        # Needs to be maintained; best practice is pass explicitly to setup-python
        default: "3.12"

permissions: {}

jobs:
  linting:
    name: "Standalone linting checks"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: "Standalone linting action"
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/standalone-linting-action@main # 2025-02-12
        with:
          config_url: ${{ inputs.config_url }}
          dependencies_url: ${{ inputs.dependencies_url }}
          remote_config: ${{ inputs.remote_config }}
          python-version: ${{ inputs.python-version }}
