---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  linting:
    name: "Standalone linting check"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: Linting action
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/linting-action@main
