---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: 📌 Audit GitHub Actions

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  check-actions:
    name: Pinned Versions
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check Pinned Versions
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/pinned-versions-action@2d122a5a8b4b45757774f469d61e26e1d66c94ad # 2025-01-14
