---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "📦 [R] Python Audit"
# Packages a development/production release on GitHub"

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        # Usually specified/extracted from the file: pyproject.toml
        description: "Python matrix versions to use for test builds (in JSON)"
        required: true
        type: string
      ARTEFACT_LOCATION:
        description: "Path/location for build artefacts"
        type: string
        required: false
        default: "dist"

permissions: {}

jobs:
  python-audit:
    name: "Python code"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read

    steps:
      - name: "Checkout repository"
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Extract project/repository naming"
        id: naming
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/project-name-compare-action@main

      - name: "⬇ Download build artefacts"
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ env.python_project_name }}
          path: ${{ inputs.artefact_location }}

      - name: "Set up Python ${{ inputs.python_version }}"
        # yamllint disable-line rule:line-length
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ inputs.python_version }}

      - name: "Install build products/dependencies"
        run: |
          # Install build products/dependencies
          echo "Upgrading: pip, setuptools"
          python -m pip install -q --upgrade pip setuptools
          echo "Installing built package(s) and dependencies"
          for wheel in ${{ inputs.artefact_location }}/*.whl; do
                  pip install -q "$wheel"
          done
          if [ -f requirements.txt ]; then
            echo "Installing dependencies from: requirements.txt"
            pip install -q -r requirements.txt
          fi

      - name: "Auditing with: pip audit"
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
