---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: "[R] Inspect Repository"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    outputs:
      # Basic repository metadata
      repository_owner:
        description: "GitHub user or organisation owning the repository"
        value: ${{ jobs.repository.outputs.repository_owner }}
      repository_name:
        description: "The Repository name"
        value: ${{ jobs.repository.outputs.repository_name }}

      # Repository content classifications
      python_project:
        value: ${{ jobs.repository.outputs.python_project }}
      node_js_project:
        value: ${{ jobs.repository.outputs.node_js_project }}
      maven_config:
        value: ${{ jobs.repository.outputs.maven_config }}
      gradle_config:
        value: ${{ jobs.repository.outputs.gradle_config }}
      jupyter_notebooks:
        value: ${{ jobs.repository.outputs.jupyter_notebooks }}
      tox_config:
        value: ${{ jobs.repository.outputs.tox_config }}

      # Tags for subsequent actions
      pushed_tag:
        value: ${{ jobs.repository.outputs.pushed_tag }}
      build_tag:
        value: ${{ jobs.repository.outputs.build_tag }}

permissions: {}

jobs:
  repository:
    name: "Check content"
    runs-on: "ubuntu-24.04"
    outputs:
      # Repository metadata
      repository_owner: ${{ steps.repository.outputs.repository_owner }}
      repository_name: ${{ steps.repository.outputs.repository_name }}

      # Classify content
      python_project: ${{ steps.content.outputs.python_project }}
      node_js_project: ${{ steps.content.outputs.node_js_project }}
      maven_config: ${{ steps.content.outputs.maven_config }}
      gradle_config: ${{ steps.content.outputs.gradle_config }}
      jupyter_notebooks: ${{ steps.content.outputs.jupyter_notebooks }}
      tox_config: ${{ steps.content.outputs.tox_config }}

      # Tags that were pushed to the repository
      pushed_tag: ${{ steps.pushed-tag.outputs.pushed_tag }}
      build_tag: ${{ steps.build-tag.outputs.build_tag }}

    permissions:
      contents: read

    #env:
    #  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Harden the runner used by this workflow
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Repository metadata"
        id: repository
        # yamllint disable-line rule:line-length
        uses: lfit/releng-reusable-workflows/.github/actions/repository-metadata-action@2a1566a557320810e89d1da3f9692292bb485313 # v0.2.12

      - name: "Classify content"
        id: content
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/repository-scan-content-action@main

      - name: "Verify pushed tag"
        id: tag-validate
        if: startsWith(github.ref, 'refs/tags/')
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-validate-semantic-action@1af2150b2d083e815b7e7994ca22fc490cf2d76c # v0.1.1
        with:
          tag: ${{ github.ref_name }}

      - name: "Pushed tag"
        if: startsWith(github.ref, 'refs/tags/')
        id: pushed-tag
        run: |
          # Pushed tag values
          if [ ${{ steps.tag-validate.outputs.semantic }} == 'true' ]; then
            pushed_tag="${{ github.ref_name }}"
            echo "Pushed semantic tag: $pushed_tag ✅"
            echo "Pushed semantic tag: $pushed_tag ✅" >> "$GITHUB_STEP_SUMMARY"
            echo "pushed_tag=$pushed_tag" >> "$GITHUB_ENV"
            echo "pushed_tag=$pushed_tag" >> "$GITHUB_OUTPUT"
          else
            echo "The pushed tag was NOT semantic: ${{ github.ref_name }} ❌"
            echo "The pushed tag was NOT semantic: ${{ github.ref_name }} ❌" \
              >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: "Get current repository tag"
        id: current-tag
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: os-climate/osc-github-devops/.github/actions/repository-tag-current-action@main

      - name: "Generate build tag"
        id: development-tag
        if: startsWith(github.ref, 'refs/tags/') != true
        uses: os-climate/osc-github-devops/.github/actions/repository-tag-next-action@main
        with:
          tag: "${{ steps.current-tag.outputs.tag }}"

      - name: "Report build tag"
        id: build-tag
        run: |
          # Build tag
          if [ -z ${{ env.pushed_tag }} ]; then
            build_tag="${{ steps.development-tag.outputs.tag }}"
          else
            build_tag="${{ env.pushed_tag }}"
          fi
          echo "Build tag: $build_tag"
          echo "Build tag: $build_tag" >> "$GITHUB_STEP_SUMMARY"
          echo "build_tag=$build_tag" >> "$GITHUB_ENV"
          echo "build_tag=$build_tag" >> "$GITHUB_OUTPUT"
