---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ [R] Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  linting:
    name: "Standalone linting checks"
    runs-on: "ubuntu-24.04"
    permissions:
      contents: read
    steps:
      - name: "Standalone linting action"
        # yamllint disable-line rule:line-length
        uses: os-climate/osc-github-devops/.github/actions/standalone-linting-action@f43c299c48b9021d41a45cf2e40edfac65e155c8 # 2025-02-05
