---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ Standalone Linting"

# yamllint disable-line rule:truthy
on:
  # Not supported when workflow contains: amannn/action-semantic-pull-request
  # workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pull-request:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: "Validate pull request title"
        # yamllint disable-line rule:line-length
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  standalone-linting:
    name: "Standalone linting checks"
    permissions:
      contents: read
    # yamllint disable-line rule:line-length
    uses: os-climate/osc-github-devops/.github/workflows/reuse-linting.yaml@main # 2025-02-12
