---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: "⛔️ Standalone Linting"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "**"
      - "!.github/**"
      - "!.*"
      - "!pdm.lock"
      - "!tox.ini"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: "Standalone linting check"
    permissions:
      contents: read
    # yamllint disable-line rule:line-length
    uses: os-climate/osc-github-devops/.github/workflows/reuse-linting.yaml@405f3ed761eb3aec868739c7d4751415d3eb21e9 # 2024-01-20
